### ISSUE TITLE
Data elements less then placeholders

### ISSUE THREAD

**Issue by epsyl** [vasa-c/go-db#39]
Hi, на одном сервере обновил php с 5.3 до 5.4 с сохранением списка расширений, но godb теперь ругается на сабж. В коде ничего не менялось, подключение:

```$db = go\DB\Storage::getInstance()->create($this->params);```

далее я делаю запросы через

```go\DB\query("SELECT * FROM ?t WHERE `id`=?i LIMIT 1", array('forms', $id), 'row')```

но почему-то массив с data пустой
вотафак?

конфиг пхп:

```
PHP 5.4.38 (cli) (built: Mar  8 2015 15:03:16) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with eAccelerator v1.0-dev, Copyright (c) 2004-2012 eAccelerator, by eAccelerator

[PHP Modules]
bz2
Core
ctype
curl
date
dom
eAccelerator
ereg
filter
gd
hash
iconv
json
libxml
mbstring
mhash
mysql
mysqli
mysqlnd
pcre
PDO
pdo_mysql
Phar
posix
Reflection
session
SimpleXML
soap
SPL
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]
eAccelerator
```

**Comment by vasa-c** [comment]
Этого не может быть, потому что не может быть никогда :)

А если через `$db->query()` ?

**Comment by Eliarh** [comment]
Советую xdebug запустить (если нет его, то от var_dump'ить)
потом проверить подсоединение
(реальный пример с работы приведу - есть продакшен и девелоп, указал, соединение к продакшену, а на уровне инишника жестко любое соединение на девелоп переключалось)

Потом выполнить тот же запрос без плейсхолдеров
ну и наконец выполнить на чистом mysqli в скрипте тот же самыый запрос

**Comment by epsyl** [comment]
@vasa-c сделал через
```
$db = go\DB\DB::create($params, 'mysql');
$pattern = "SELECT * FROM ?t";
$data = array('forms');

$items = $db->query($params, $data, 'assoc');
```

опять ругается :)
Data elements (1) more than the placeholders (0)

**Comment by epsyl** [comment]
если убираю плейсхолдеры

````$pattern = "SELECT * FROM `ezso__forms`";
$data = array();```

то получаю ошибки
```
# php test.php
PHP Warning:  mysqli::query() expects parameter 1 to be string, array given in _/lib/goDB/Implementations/Mysql.php on line 61

Warning: mysqli::query() expects parameter 1 to be string, array given in _/lib/goDB/Implementations/Mysql.php on line 61
PHP Notice:  Array to string conversion in _/lib/goDB/Exceptions/Query.php on line 41

Notice: Array to string conversion in _/lib/goDB/Exceptions/Query.php on line 41
PHP Fatal error:  Uncaught exception 'go\DB\Exceptions\Query' with message 'Error SQL "Array"; error="" [#0]' in _/test.php:26
Stack trace:
#0 _/lib/goDB/DB.php(105): go\DB\DB->plainQuery(Array, 'assoc')
#1 _/test.php(26): go\DB\DB->query(Array, Array, 'assoc')
#2 {main}
  thrown in _/test.php on line 26

Fatal error: Uncaught exception 'go\DB\Exceptions\Query' with message 'Error SQL "Array"; error="" [#0]' in _/test.php:26
Stack trace:
#0 _/lib/goDB/DB.php(105): go\DB\DB->plainQuery(Array, 'assoc')
#1 _/test.php(26): go\DB\DB->query(Array, Array, 'assoc')
#2 {main}

```

какая-то наркомания, на соседнем сервере с 5.3 и 5.6 все окей

**Comment by epsyl** [comment]
вообщем, на данный момент решилось все обновлением php до 5.6...

**Comment by vasa-c** [comment]
Прикольно. Возможно палёная версия какая-то.
Мне он сейчас предлагает до неё обновиться. Цыкотно теперь.

**Comment by epsyl** [comment]
@vasa-c ну мне вобщем-то похуй, главное чтобы работало, не ставл время тратить - выяснять причины такого поведения на 5.4.38, чего и всем советую
