### ISSUE TITLE
Расширенный ?where

### ISSUE THREAD

**Issue by vasa-c** [vasa-c/go-db#45]

**Comment by vasa-c** [comment]
https://github.com/vasa-c/go-db/wiki/where

**Comment by mkedo** [comment]
По поводу вики:

> Пустой массив приводится к 1 (выборка всех строк)

Сейчас приводится к 1=1

>FALSE - это приводится к 0.

к 1=0

> Любой другой скаляр, в том числе NULL - приводится к 1.

к 1=1
