### ISSUE TITLE
Расширенный ?set

### ISSUE THREAD

**Issue by vasa-c** [vasa-c/go-db#46]
col=col+1

**Comment by epsyl** [comment]
:+1:

**Comment by vasa-c** [comment]
@epsyl а ты пользуешься, что ли? 

Как оказывается, это уже можно :)

```php
        $set = [
            'column' => ['col' => 'column', 'value' => 2]
        ];
        
        $db->query('UPDATE `table` SET ?set', [$set]);
```

```
UPDATE `table` SET `column`=`column`+2
```

**Comment by epsyl** [comment]
@vasa-c пользуюсь, добавь в доку
я юзал `SET ?c=?c ?q`
`['column','column','+2']`

**Comment by vasa-c** [comment]
https://github.com/vasa-c/go-db/wiki/set

**Comment by epsyl** [comment]
@vasa-c подскажи, как сделать ``date`=NOW()`
если ?col func требует обязательного присутствия `col` или `value`

**Comment by vasa-c** [comment]
@epsyl обновись.

https://github.com/vasa-c/go-db/wiki/cols
```php
$col = [
    'func' => 'NOW',
];
$table->update(['x' => $col]);
```

```sql
UPDATE `table` SET `x`=NOW()
```

**Comment by epsyl** [comment]
@vasa-c все ок, храни тебя иисус
