### ISSUE TITLE
[Предложение] Подставлять в запрос значния соотвествующие типу значений в php. (Модификтор auto?)

### ISSUE THREAD

**Issue by mkedo** [vasa-c/go-db#61]
Проблема: 
Сейчас все плейсхолдеры (без модификаторов) расценивают данные (за исключением null), как строки 
 и соответсвенно представляют их в запросе строкой.
Обычно это нормально работает, однако, иногда нужно вставлять числа именно как числа, иначе PostgreSQL кидает ошибку.

Пример:
Есть некая таблица:
`
CREATE TABLE example (
 id integer,
 name character varying
);
`
Хочу вставить в неё сразу много строк:
`
INSERT INTO example
SELECT * FROM (VALUES 
 ?v
) ex(id, name)
/* Здесь обычно дополнительное условие WHERE. Опущено для краткости */
;
`
Что преобразуется примерно в такой запрос:
`
INSERT INTO example
SELECT * FROM (VALUES 
 ('1', 'str 1'),
 ('2', 'str 2')
) ex(id, name);
`
Который падает с ошибкой:

ОШИБКА: колонка "id" имеет тип integer, а выражение - text
SQL-состояние: 42804

Чтобы убрать ошибку, нужен запрос вида:
`
INSERT INTO example
SELECT * FROM (VALUES 
 (1, 'str 1'),
 (2, 'str 2')
) ex(id, name);
`

Т.к. плейсхолдер ?v не поддерживает управлениями типов отдельных колонок, то я сейчас нет возможности оставить числа числами в ?v.

Предложение:
Может стоит ввести модификатор, к примеру, auto, который бы в зависимости от типа значения в php подставлял значения соответсвующего типа в запрос?

**Comment by vasa-c** [comment]
@mkedo можно и не вводить модификатор, а всегда так делать.
Pg не расстроится если ей, наоборот, вместо строки придёт число?

**Comment by mkedo** [comment]
@vasa-c 
В данном запросе не расстроится. Я тоже за "не вводить модификатор", но без модификатора теоретически может поломаться обратная совместимость.
Например,
`SELECT * FROM example WHERE name = 1`
Упадет `[Err] ОШИБКА:  оператор не существует: character varying = integer`
Хотя вероятность встретить такое в коде мала.

Думаю сделать без модификатора для всех плейсхолдеров, погонять денек-другой у себя на проекте, и если ничего не вылезет, то сделаю pull request.

**Comment by vasa-c** [comment]
Есть класс Compat: https://github.com/vasa-c/go-db/blob/master/goDB/Compat.php
для настроек совместимости с легаси.
