### ISSUE TITLE
where now()

### ISSUE THREAD

**Issue by djAlba** [vasa-c/go-db#64]
Чего-то с размаху :) не получается сделать where col_date <= NOW() +  INTERVAL 1 WEEK
такой вариант не реализован, или у меня голова не справляется? :)

пробовал так: $where["col_date "] = array("op" => "<=", "value" => "NOW() + INTERVAL 1 WEEK");
ну, по крайней мере это единственный вариант, который похож на правду. если добавлять "func" => "NOW" то на функцию вообще кладётся болт. а этот вариант - добавляет (что естественно), кавычки и, сравнивает дату с текстом.
если в func вписать какой-нить "DATE", а в value "NOW() + INTERVAL 1 WEEK" - то функция просто игнорируется.

подскажете, куда копать?

**Comment by vasa-c** [comment]
Ну, столь сложные выражения, скорее всего нельзя, в $where засунуть.
Как вариант, можно сделать, чтобы туда можно было любой SQL класть в крайнем случае.

А просто в запросе нельзя это условие написать?

**Comment by djAlba** [comment]
В условии и написано. просто задумал унифицировать все свои запросы, и подумал, что может у меня ума не хватает. :)
