### ISSUE TITLE
Проблемка с ?order, больше 1 поля

### ISSUE THREAD

**Issue by epsyl** [vasa-c/go-db#65]
Простые order (['rating'=>false]) работают ок
Если добавить еще поля для сортировки ([['rating' => false, 'id' => true]]) — то выдает ошибку

```
Data for ?col has invalid format: "required `col`, `value` or `func` field"
```

и еще вопросец, как юзать алиасы таблиц в order? к примеру, мне нужно сортировать по 
```
I.`rating` DESC, U.`name` ASC
```

**Comment by vasa-c** [comment]
Как сказал мой программист "наверное он суёт не туда".
Покажи пример.

> как юзать алиасы таблиц в order?

Там без таких наворотов.
Это востребованно?

**Comment by epsyl** [comment]
@vasa-c 
кстати да, неправильно.. позор 
`'order' => [['rating'=>false],['stars_counter'=>false]]`
а нужно было `'order' => ['rating'=>false,'stars_counter'=>false]`

на счет алиасов - хз, востребовано или нет, просто интересно)
