### ISSUE TITLE
WHERE при использовании JOIN

### ISSUE THREAD

**Issue by freebuu** [vasa-c/go-db#68]
Всем дртатути!
Пример запроса:
```
$where = [
'id' => 120
];
SELECT * FROM `tbl1` LEFT JOIN `tbl2` ON (`tbl1`.id` = `tbl2`.`id_from_`tbl1`) WHERE ?where
```
Логично, что выдает ошибку column id is ambiguous
Если делать 'tbl1.id' => 120 - то парсит как `tbl1.id1` - опять же ошибка
Если делать 'tbl1`.`id' => 120 - то парсит как ```tbl1``.``id1```

В общем хотелось бы иметь возможность обращаться в where к конкретным таблицам

**Comment by freebuu** [comment]
парсер сжирает апострофы около примеров парсера - в первом случае по одному перед и после, во втором по три

**Comment by mkedo** [comment]
Плейсхолдер ?where такого не предусматривает и, имхо, вряд ли будет, т.к
ключами массива могут быть только integer или string, т.е таблицу дополнительно не указать.
Придется условие генерировать самому.

**Comment by vasa-c** [comment]
Дратути, дратути...

У WHERE есть расширенный формат: https://github.com/vasa-c/go-db/wiki/where#%D0%A0%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82

Но я бы не советовал им злоупотреблять.

**Comment by freebuu** [comment]
о, не было там раньше возможности указания таблицы!!!111
_но скорее всего просто я слеповат_
Благодарю
